version: '3.8'

services:
  game:
    build: ./coregameservice/
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - game

