version: '3.8'

services:
  frontend:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "808:80"
     
  # apigateway:
  #   build: ./apigateway
  #   depends_on:
  #     - authservice
  #     - mailservice
  #     - usermanagement

  # authservice:
  #   build: ./authservice

  # mailservice:
  #   build: ./mailservice
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy


  # usermanagement:
  #   build: ./usermanagement

    
  # rabbitmq:
  #   image: rabbitmq:3.8.17-management
  #   healthcheck:
  #     test: rabbitmq-diagnostics check_port_connectivity
  #     interval: 30s
  #     timeout: 30s
  #     retries: 10
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
