version: '3.8'

services:
  frontend:
    container_name: frontend
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "808:80"
     
  apigateway:
    container_name: apigateway
    build: ./apigateway
    depends_on:
      - authservice
      - mailservice
      - usermanagement
    ports:
      - "8000:8000"

  authservice:
    container_name: authservice
    build: ./authservice

  mailservice:
    container_name: mailservice
    build: ./mailservice
    depends_on:
      rabbitmq:
        condition: service_healthy


  usermanagement:
    container_name: usermanagement
    build: ./usermanagement
    ports:
      - "8004:8004"

    
  rabbitmq:
      container_name: rabbitmq
      image: rabbitmq:3.8.17-management
      ports:
        - "5672:5672"
        - "15672:15672"
      healthcheck:
        test: ["CMD", "rabbitmqctl", "node_health_check"]
        interval: 30s
        timeout: 10s
        retries: 5